import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">

      <body className={`bg-slate-200 overflow-x-hidden`}>
        <div className='bg-gradient-to-l to-blue-800 from-blue-900 w-full h-[1rem]'></div>
        {children}
      
      </body>
    </html>
  )
}
